
test_data_path:  /mnt/external/data/BraTS_3D
save_path:      /mnt/external/results_nicoc/3D_final_final/full_shot_ensamble
checkpoint_path: ./experiments_3D/3D_final_plots/3D_full_shot_prompt_ensamble/epoch_20.pth
dataset:         brats
features_list:   [3,4,11]

temperature_scale: 0.2
depth:             32      # single‐slice inference
gt_root:           /mnt/external/data/BraTS_3D
dice_threshold:    null
seed:              111
prompt_ensemble:   True
prompt_path:       ./configs/prompts_brats.yaml
