
test_data_path: ./data/BraTS_3D
save_path:       ./results/full_shot_ensemble
gt_root:    ./data/BraTS_3D
dice_threshold:  ./results/full_shot_ensemble
checkpoint_path: ./experiments_3D/3D_final_plots/3D_full_shot_prompt_ensamble/epoch_20.pth
depth:      32
dataset:    brats
seed: 111
prompt_ensemble:   True
prompt_path:       ./configs/prompts_brats.yaml