
test_data_path: /mnt/external/data/BraTS_3D
save_path:      /mnt/external/results_nicoc/3D_final_final/full_shot_2d_replicated
preds_root: /mnt/external/results_nicoc/3D_final_final/full_shot_2d_replicated
gt_root:    /mnt/external/data/BraTS_3D
features_list:   [3,4,11]

checkpoint_path: ./experiments_3D/3D_final_plots/full_shot_2D_replicated/epoch_17.pth
dice_threshold: /mnt/external/results_nicoc/3D_final_final/full_shot_2d_replicated
depth:      1
dataset:    brats
seed: 111
