
test_data_path: ./data/BraTS_3D
save_path:      ./results/full_shot_2d
preds_root: ./results/full_shot_2d
gt_root:    ./data/BraTS_3D
features_list:   [3,4,11]

checkpoint_path: ./experiments_3D/3D_final_plots/full_shot_2D_replicated/epoch_17.pth
dice_threshold: ./results/full_shot_2d
depth:      1
dataset:    brats
seed: 111
