
train_data_path: ./data/BraTS_3D
save_path:       ./experiments_3D/3D/3_patient
dataset:         brats
features_list:   [3,4,11]

epoch:           15
learning_rate:   1e-4
batch_size:      1
depth:           32     # single-slice
image_size:      256
print_freq:      10
save_freq:       1
temperature:     0.2
prompt_ensemble: True
prompt_path: ./configs/prompts_brats.yaml
patient_seed_path: ./patients_seeds/patients_k=30.txt